### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file (Python 3.6.7 OpenCV3.4.2)

### ISSUE THREAD

**Issue by kking124** [whitelok/watermark-remover#10]
I'm having the same issue as Issue #6 except I am running Python 3.6.7.

**Comment by kking124** [comment]
Nevermind - the issue was that train.sh calls python 3.7 on Ubuntu 18.04 - running the following command instead:

```
python3 main.pyc --mode train --dataset demo --iters 3 --watermark_threshold 0.7 --save_result true
```

corrected the issue.

**Comment by Photokeep** [comment]
I have the same error even i switched python3  in my MacOS.

**Comment by whitelok** [comment]
Please run with Python 3.6.5. Will provide a docker image for pack the environment.

**Comment by whitelok** [comment]
please running the code in docker: `docker pull whitelok/watermark-remover`
Closing this issue by provided the docker runtime
