### ISSUE TITLE
"Can't use on your computer" when trying to run train.sh

### ISSUE THREAD

**Issue by tim777z** [whitelok/watermark-remover#12]
"Can't use on your computer" when trying to run train.sh
![image](https://user-images.githubusercontent.com/11827348/57142038-e46a6280-6dbb-11e9-93e7-262e4030f6e2.png)

**Comment by whitelok** [comment]
please using the latest submit code.

**Comment by tim777z** [comment]
Uhm, I am using the latest code...

**Comment by whitelok** [comment]
please running the code in docker: `docker pull whitelok/watermark-remover`
Closing this issue by provided the docker runtime

**Comment by xaionaro** [comment]
I have the same problem. But also:

```
$ docker pull whitelok/watermark-remover
Using default tag: latest
Error response from daemon: manifest for whitelok/watermark-remover:latest not found
```

Please re-open the issue.

And the code is closed so I cannot fix (or even just investigate) the bug by myself.

**Comment by xaionaro** [comment]
Also I've built the docker image manually (using `watermark-dockerfile`) and received the same error in the container:
```
root@adac1e01339f:~/watermark-remover# ./train.sh 
Can't use on your computer, sorry.
```
