### ISSUE TITLE
seems the remove is broken

### ISSUE THREAD

**Issue by r36031026** [whitelok/watermark-remover#13]
![image](https://user-images.githubusercontent.com/19781688/57194597-39080c00-6f7b-11e9-9764-f69143eee356.png)
the W_201_120_3 is not what I generated from the picture , but still need this file.... pretty strange

**Comment by whitelok** [comment]
remove mode is not ok from now. need more time to finish such feature.

**Comment by whitelok** [comment]
not support  Windows..
