### ISSUE TITLE
python 3.6.8 无法执行，能否提供完整源代码。

### ISSUE THREAD

**Issue by alleniver** [whitelok/watermark-remover#14]
你好，是否硬性需要3.6.5版本，我用3.6.8版本执行有问题，能否提供一下源码供参考，只做技术参考，不会传播和商用。如果可以的话，请发一下我邮箱hu030152#gmail.com,谢谢！

**Comment by whitelok** [comment]
please running the code in docker: `docker pull whitelok/watermark-remover`
Closing this issue by provided the docker runtime

**Comment by alleniver** [comment]
好的,谢谢,我看看!
