### ISSUE TITLE
removal result

### ISSUE THREAD

**Issue by chen849157649** [whitelok/watermark-remover#17]
![fotolia_152586](https://user-images.githubusercontent.com/32058220/62756275-b32fbb80-baa9-11e9-89c5-099bc1afb2ab.jpg)
![fotolia_539921](https://user-images.githubusercontent.com/32058220/62756277-b3c85200-baa9-11e9-8760-eb4c79f44417.jpg)
![fotolia_592458](https://user-images.githubusercontent.com/32058220/62756279-b460e880-baa9-11e9-9a41-ccac3a1af279.jpg)
![fotolia_688089](https://user-images.githubusercontent.com/32058220/62756280-b4f97f00-baa9-11e9-9fab-7dc9379014fd.jpg)
![fotolia_781992](https://user-images.githubusercontent.com/32058220/62756283-b5921580-baa9-11e9-888a-7ba8934b103b.jpg)

The watermark removal is not very clean, and there are traces on the border. Can you give me some advice? thank you

**Comment by whitelok** [comment]
seem need algo update, will review when I free from work.

**Comment by whitelok** [comment]
close and refer to https://github.com/whitelok/watermark-remover/issues/29
