### ISSUE TITLE
manifest unknown when running docker pull

### ISSUE THREAD

**Issue by dlwalter** [whitelok/watermark-remover#18]
When I run 

`docker pull whitelok/watermark-remover`

I get the following error:

```
Using default tag: latest
Error response from daemon: manifest for whitelok/watermark-remover:latest not found: manifest unknown: manifest unknown
```

**Comment by whitelok** [comment]
[fixed] in https://github.com/whitelok/watermark-remover/commit/caf368bf6a44e30ca1c66c817c5073ff9b9541b2
should be docker pull whitelok/watermark-remover:v1.0
