### ISSUE TITLE
Problem with the imports in "./autowatermarkremoval/solver.py"

### ISSUE THREAD

**Issue by carloscallejo** [whitelok/watermark-remover#19]
I am trying to run the solver.pyc code to remove some watermarks from my own folder with watermarked pictures. I'm using this command:

 `python3 ./autowatermarkremoval/solver.pyc --path ../input_pictures/
`

Nevertheless, this does not work. I am getting the following error:

`ImportError: cannot import name 'utils'
`

I have opened the compiled code of solver.pyc with 'uncompyle6' to see the source code, and I see that there are many relative imports that are done. I made some modifications to these imports but I couldn't manage to make it work. Any ideas why this is failing?

Additionally, I would be really grateful if you could make a little bit more detailed 'readme'.

**Comment by whitelok** [comment]
according  to the shown up  running code. you can `export PYTHONPATH=${PWD}/autowatermarkremoval:$PYTHONPATH` and try and feedback.
