### ISSUE TITLE
Cannot build the docker image from master

### ISSUE THREAD

**Issue by dondre** [whitelok/watermark-remover#34]
When I try I get the following error:

`[ 77%] Built target opencv_ccalib
CMakeFiles/Makefile2:6925: recipe for target 'modules/rgbd/CMakeFiles/opencv_rgbd.dir/all' failed
make[1]: *** [modules/rgbd/CMakeFiles/opencv_rgbd.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c mkdir -p ~/opencv/build && cd ~/opencv/build &&     cmake -D CMAKE_BUILD_TYPE=RELEASE           -D CMAKE_INSTALL_PREFIX=/usr/local           -D WITH_IPP=OFF           -D WITH_CUDA=OFF           -D WITH_OPENCL=OFF           -D BUILD_TESTS=OFF           -D PYTHON_DEFAULT_EXECUTABLE=$(which python3)           -D BUILD_PERF_TESTS=OFF           -D OPENCV_ENABLE_NONFREE=ON           -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules           .. &&      make -j"$(nproc)" install &&      ln -s /usr/local/include/opencv4/opencv2 /usr/local/include/opencv2' returned a non-zero code: 2`

**Comment by whitelok** [comment]
OK, I will check this ASAP.

**Comment by whitelok** [comment]
Thanks for someone's suggestion. ALL CODE IN THIS WILL BE DELETE FOREVER. So no support anymore.

Closing
