### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file

### ISSUE THREAD

**Issue by vantinhuynh** [whitelok/watermark-remover#35]
@whitelok 
I got the error "RuntimeError: Bad magic number in .pyc file" when I tried to execute this application

python3 main.pyc --mode train --dataset demo --iters 3 --watermark_threshold 0.7 --save_result true

**Comment by coconut009** [comment]
python virtual environment 3.6.5 + all the required dependencies

**Comment by whitelok** [comment]
Thanks for someone's suggestion. ALL CODE IN THIS WILL BE DELETE FOREVER. So no support anymore.

Closing
