### ISSUE TITLE
Files in order

### ISSUE THREAD

**Issue by arthurwolf** [whitelok/watermark-remover#37]
Hello!

I'm trying to get this to work for videos instead of just static images.
I've got it mostly working, except it randomizes the filenames when reading the original folder, and the output filenames do not match the input filenames, so I have no convenient ways to keep the video frames in the right order.
Can the code be edited to fix this? Anyone has an idea how I could get the order to be enforced?

Cheers!

**Comment by whitelok** [comment]
I think I should make this repo as a "lib" for you, because tool is hard to full fill your need.
I will add this feature next week.

**Comment by whitelok** [comment]
Thanks for someone's suggestion. ALL CODE IN THIS WILL BE DELETE FOREVER. So no support anymore.

Closing
