### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by wyhgood** [whitelok/watermark-remover#4]
泊松重构图像您是怎么做的呢
how to do  the possion reconstruct using gradient of watermark image?

**Comment by whitelok** [comment]
这个我找到论文了 在实现相应的库 可能不会放在这个repository里面的

2017-10-20 9:58 GMT+08:00 wyhgood <notifications@github.com>:

**Comment by wyhgood** [comment]
我在网上搜到个代码，说是利用图像梯度可以重建图像，但是需要知道图像的边缘信息。 你找到的论文是不是也需要边缘信息呢  谢谢

**Comment by wyhgood** [comment]
如果只是根据梯度， 估算出的matted watermark 应该不准确， 我不太清楚这样的初始值对接下来的优化算法 影响大不大

**Comment by whitelok** [comment]
如果简单地根据图像估算matted watermark 影响很大 效果真心没预期的好 所以我现在还在看有没有论文实现这个点
![untitled](https://user-images.githubusercontent.com/1612381/31882299-e5192694-b818-11e7-87c3-041998a5af51.png)

**Comment by whitelok** [comment]
我在看的主要Possion Image Reconstruction 是这个 https://dsp.stackexchange.com/questions/6223/gradient-domain-reconstruction-scaling-problem 
有空的话加个微信吧 这里你要是更新了我没提示

**Comment by whitelok** [comment]
我微信是：Karl34787333

**Comment by wyhgood** [comment]
我微信号 Shyboyhero  加我下吧

**Comment by whitelok** [comment]
暂时找到的解决方案的raw code在这里http://web.media.mit.edu/~raskar/photo/code.pdf

**Comment by whitelok** [comment]
Already implemented closing this issue.

**Comment by binxxx** [comment]
请问你找到的解决方案中，`boundary_image`应该怎么来定？
