### ISSUE TITLE
求教一个问题

### ISSUE THREAD

**Issue by Ethan4869** [whitelok/watermark-remover#5]
你好，我最近刚在学习这篇文章，有些地方没有看懂，求教~
比如Eq.5，应该是解释为什么随着K增大，梯度的中位数会收敛于水印部分。但是这部分的公式推导不是很清楚，▽是计算梯度的意思，E[] 是什么意思？exception吗？  但是等式第二步不清楚是怎么转化的，文章里面只是说乘法导数。可以指导一下吗？多谢！

**Comment by whitelok** [comment]
E[] 应该就是exception 的意思。Eq. 5第一步是对Eq.1左右求期望，第二步中E[delta_W_supper_m] = delta_W_supper_m我的理解是因为：使用了Poisson Reconstruction重构了Eq.4。Poisson Reconstruction的性质使得W_supper_m = aW 成立。

**Comment by whitelok** [comment]
Already implemented. Closing this issue.
