### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file when running with python3.7

### ISSUE THREAD

**Issue by martinschaef** [whitelok/watermark-remover#6]
I get a RuntimeError: Bad magic number in .pyc file when running with python3.7
Is 3.6.5 a hard requirement?

**Comment by whitelok** [comment]
Yes. Or I can give you a python3.7 version. Is it ok for you?

**Comment by Dao258** [comment]
Hey, @whitelok 
if you can provide the 3.7.1 version 
that would be a great!

Appreciated !

**Comment by martinschaef** [comment]
Yeah, a 3.7 branch would be nice. Any reason why you don't allow ppl to build it from source?

**Comment by whitelok** [comment]
Hi all, Py3.7.2 version is upload in https://drive.google.com/open?id=15zt8ZXr4yZlqx95QzdJ1DKSx-NKitBPN
Please feel free to ping me if there are any issue.
And I am consulting my lawyer about the license. I will release all source code after getting result.

Thanks for feedback.

**Comment by whitelok** [comment]
Closing this issue for https://github.com/whitelok/watermark-remover/issues/6#issuecomment-454255363 . Reopen if there are more request

**Comment by 308butterfly** [comment]
Good luck with the licensing.
