### ISSUE TITLE
Keep getting _tkinter module error

### ISSUE THREAD

**Issue by jeanbverroken** [whitelok/watermark-remover#8]
I have installed the requirements and python3-tk.
Not sure but why when running bash demo.sh I get the follower error.

> 
> `Traceback (most recent call last):
>   File "./main_solver.py", line 5, in <module>
>   File "./autowatermarkremoval/solver.py", line 9, in <module>
>   File "/home/user/venv3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
>     _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
>   File "/home/user/venv3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
>     [backend_name], 0)
>   File "/home/user/venv3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
>     from . import tkagg  # Paint image to Tk photo blitter extension.
>   File "/home/user/venv3/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
>     from six.moves import tkinter as Tk
>   File "/usr/lib/python3/dist-packages/six.py", line 92, in __get__
>     result = self._resolve()
>   File "/usr/lib/python3/dist-packages/six.py", line 115, in _resolve
>     return _import_module(self.mod)
>   File "/usr/lib/python3/dist-packages/six.py", line 82, in _import_module
>     __import__(name)
>   File "/usr/lib/python3.6/tkinter/__init__.py", line 36, in <module>
>     import _tkinter # If this fails your Python may not be configured for Tk
> ModuleNotFoundError: No module named '_tkinter'
> `

**Comment by whitelok** [comment]
if you are in Ubuntu please install tk package: `sudo apt-get install python3.6-tk`

**Comment by jeanbverroken** [comment]
Doesn't work for me, same error. 
Edit: I am on elementary OS
Edit2: I just saw; when `running sudo apt-get install python3.6-tk`
In the command line it states : `Note, selecting 'python3-tk' instead of 'python3.6-tk'`

**Comment by whitelok** [comment]
I  will fixed this before Mar 3th. Thanks for your report.

**Comment by jeanbverroken** [comment]
My Python version is 3.6.7. Should I downgrade to 3.6.5?

**Comment by whitelok** [comment]
not need. I can handle it. Will update progress here.

**Comment by whitelok** [comment]
Hi jeanbverr, I have fixed in new push. Could you help me to verify?
https://github.com/whitelok/watermark-remover/commit/a0cc9a8f74846c8f5a3420005f908a37c0126362

**Comment by whitelok** [comment]
closed. And will reopen when this issue can be reproduced
